#E-Commerce sales
#Find the total sales, total profit, and total number of orders.
SELECT * FROM ECOMMERCESALES;
SELECT ROUND(SUM(SALES),2) AS TOTAL_SALES,
ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT,
COUNT(`ORDER ID`) AS TOTAL_PROFIT
FROM ECOMMERCESALES;

#Find the top 10 products generating the highest sales.
SELECT `PRODUCT NAME`,
SUM(SALES) AS `HIGHEST PRODUCT SALE` 
FROM ECOMMERCESALES
GROUP BY `PRODUCT NAME`
ORDER BY 2 DESC;

#Show total sales and profit for each region.
SELECT REGION,
ROUND(SUM(SALES),2) AS `TOTAL SALES`,
ROUND(SUM(PROFIT),2) AS `TOTAL PROFIT`
FROM ECOMMERCESALES
GROUP BY REGION;


#Find how many orders were placed using each payment mode.
SELECT `PAYMENT MODE`,
COUNT(`ORDER ID`) AS TOTAL_ORDER
FROM ECOMMERCESALES
GROUP BY 1;

#Calculate average discount offered in each category.

SELECT CATEGORY,
ROUND(AVG(DISCOUNT),2) AS AVG_DISCOUNT
FROM ECOMMERCESALES
GROUP BY 1;

#Top 5 Customers by Revenue
SELECT `CUSTOMER NAME`,
ROUND(SUM(SALES),2) AS REVENUE 
FROM ECOMMERCESALES
GROUP BY 1
ORDER BY REVENUE DESC
LIMIT 5;

#Calculate total sales for every month.
SELECT MONTHNAME(`ORDER DATE`) AS MONTHS,
ROUND(SUM(SALES),2) AS TOTAL_SALES_BY_MONTH 
FROM ECOMMERCESALES
GROUP BY 1;

#Find the city with highest total sales.
SELECT CITY,
ROUND(SUM(SALES),2) AS HIGHEST_SALES
FROM ECOMMERCESALES
GROUP BY CITY
ORDER BY HIGHEST_SALES DESC
LIMIT 1;

#Calculate each category's contribution to total sales.
SELECT * FROM ECOMMERCESALES;
#Find products whose total quantity sold is greater than average quantity sold across all products.
SELECT AVG(QUANTITY) FROM ECOMMERCESALES;
SELECT `PRODUCT NAME`,SUM(QUANTITY) AS TOTAL_QTY_AS_PRODUCT FROM ECOMMERCESALES
GROUP BY `PRODUCT NAME`
HAVING TOTAL_QTY_AS_PRODUCT>(
SELECT AVG(QUANTITY) FROM ECOMMERCESALES
);
#What are the top-performing and lowest-performing products within each distinct business category based on total generated profit?"
SELECT CATEGORY,`PRODUCT NAME`,SUM(PROFIT) AS TOTAL_PROFIT,
RANK() OVER(PARTITION BY CATEGORY ORDER BY SUM(PROFIT)) AS RANK1
FROM ECOMMERCESALES
GROUP BY 1,2;

#Which specific product ranks as the second-highest sales generator within each individual product category, and how far behind is it from the top performer?
WITH NEWTABLE AS(
	SELECT 
		 CATEGORY,
		`PRODUCT NAME`,
		SUM(SALES) AS TOTAL_SALES,
        DENSE_RANK() OVER(PARTITION BY CATEGORY ORDER BY SUM(SALES) DESC)
        AS SALES_RANK
        FROM ECOMMERCESALES
        GROUP BY 1,2
)
SELECT CATEGORY ,
`PRODUCT NAME`, 
TOTAL_SALES
FROM NEWTABLE
WHERE SALES_RANK=2;

#What is the Month-over-Month (MoM) sales growth rate.
SELECT * FROM ECOMMERCESALES;

WITH MONTHLYSALES AS(
SELECT 
YEAR(`ORDER DATE`) AS YEARS,
MONTH(`ORDER DATE`) AS MONTHS,
ROUND(SUM(SALES),2) AS CURRENT_SALE
FROM ECOMMERCESALES
GROUP BY 1,2
),
CALCULATEDSALES AS(
	SELECT YEARS,
    MONTHS,
    CURRENT_SALE,
    LAG(CURRENT_SALE,1) OVER(ORDER BY YEARS,MONTHS) AS PREVIOUS_SALE
    FROM MONTHLYSALES
)
 SELECT YEARS,MONTHS,
ROUND(
((CURRENT_SALE-PREVIOUS_SALE)/NULLIF(PREVIOUS_SALE,0))*100,2
) AS MOM_GROWTH
FROM CALCULATEDSALES;

#Find customers whose total sales are greater than the average customer sales.
SELECT * FROM ECOMMERCESALES;
WITH CUSTOMERTOTAL AS(
SELECT
	`ORDER ID`,
    `CUSTOMER NAME`,
    SUM(SALES) AS TOTAL_CUSTOMER_SALES
FROM ECOMMERCESALES
GROUP BY 1,2
)
SELECT `ORDER ID`,
	`CUSTOMER NAME`,
    ROUND(TOTAL_CUSTOMER_SALES,2) AS TOTAL_SALES
    FROM CUSTOMERTOTAL
WHERE TOTAL_CUSTOMER_SALES>(
SELECT AVG(TOTAL_CUSTOMER_SALES) FROM CUSTOMERTOTAL
)ORDER BY TOTAL_SALES